#!/bin/sh
# ****************************************************************
# * Copyright (C) 2017 TOSHIBA CORPORATION. All rights reserved. *
# ****************************************************************
#

# Used commands
vmware=`which vmware-view`
citrix=`ls /opt/Citrix/ > /dev/null 2&>1`

if [ -n "$vmware" ]; then
	echo 1				# VMware
elif [ -n "$citrix" ]; then
	echo 0				# Citrix
fi