#!/bin/sh

set -e

alsa_set_default_card() {
	aplay -l | awk -F \: '/,/{print $2}' | awk '{print $1}' | uniq | grep PCH &>/dev/null
	[ $? -eq 0 ] || exit 0 
	# change default card
	sed -i "s@^defaults.ctl.card.*@defaults.ctl.card PCH@g" /usr/share/alsa/alsa.conf
	sed -i "s@^defaults.pcm.card.*@defaults.pcm.card PCH@g" /usr/share/alsa/alsa.conf
	# change default device
	dev=$(aplay -l | awk -F \: '/,/{print $2}' | grep PCH | awk '{print $NF}')
	sed -i "s@^defaults.pcm.device.*@defaults.pcm.device $dev@g" /usr/share/alsa/alsa.conf
}

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting alsa set default card"
    alsa_set_default_card 
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/alsa-set-def-card {start}"
    exit 1
esac

