#!/bin/sh

set -e

amixer_sset() {
	amixer sset Master 100% unmute
	amixer sset Headphone 67% unmute
	amixer sset Speaker 100% unmute
	amixer sset Mic 61% unmute
	amixer sset Capture 61% cap
}

# Get lsb functions
. /lib/lsb/init-functions

AMXSSET="amixer_sset"

case "$1" in
  start)
    log_begin_msg "Starting amixer sset"
    $AMXSSET
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/amixer-sset {start}"
    exit 1
esac

