#!/bin/sh

set -e

# Get lsb functions
. /lib/lsb/init-functions

CHMOD=$(chmod 0666 /var/log/SelectTouchPad)

case "$1" in
  start)
    log_begin_msg "Starting chmod SelectTouchPad"
    $CHMOD
	log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/chmod-selecttp {start}"
    exit 1
esac

