#!/bin/sh

# Get lsb functions
. /lib/lsb/init-functions

LINRE="/var/tmp/linuxreggen"

[ -e /var/tmp/linuxreggen ] || exit 0

case "$1" in
  start)
    log_begin_msg "Starting linuxreggen"
    $LINRE
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/linuxreggen {start}"
    exit 1
esac

