#!/bin/sh

set -e

# Get lsb functions
. /lib/lsb/init-functions

LOCALEGEN="locale-gen"

case "$1" in
  start)
    log_begin_msg "Starting amixer sset"
    $LOCALEGEN
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/locale-gen {start}"
    exit 1
esac

