#!/bin/sh

set -e

# Get lsb functions
. /lib/lsb/init-functions

mount_filesystems () {
	# mount a tmpfs on /dev/shm
	if [ ! -d /dev/shm ]; then
		mkdir --mode=755 /dev/shm
	fi
	mount -t tmpfs tmpfs /dev/shm

	# mount a devpts on /dev/pts
	if [ ! -d /dev/pts ]; then
		mkdir --mode=755 /dev/pts
	fi
	mount -t devpts devpts /dev/pts
}

case "$1" in
  start)
    log_begin_msg "Starting mountdevsubfs"
    mount_filesystems
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/mountdevsubfs {start}"
    exit 1
esac

