#!/bin/sh

set -e

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting pcscd daemon"
	pcscd
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/pcscd {start}"
    exit 1
esac

