#!/bin/sh

set -e

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting pulseaudio service."
    pulseaudio --system -D -v
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/pulseaudio-sysmod {start}"
    exit 1
esac
