#!/bin/sh
### BEGIN INIT INFO
# Provides:          touchpad-init
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Init touchpad
# Description:       Init touchpad
### END INIT INFO

set -e

TOUCHPAD="/usr/bin/touchpad-init"
SYNAPTIC="/usr/bin/Synaptic_sst"
SENS="/etc/syntp_sensitive.conf"

[ -x "$TOUCHPAD" ] || exit 0
[ -x "$SYNAPTIC" ] || exit 0
[ -e "$SENS" ] || echo "4" >/etc/syntp_sensitive.conf

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting touchpad-init"
    $TOUCHPAD
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping touchpad-init"
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/touchpad-ini {start|stop|restart|reload|force-reload|status}"
    exit 1
esac

