#!/bin/sh

#========================================================================
# TZCS Control Panel
# Execute Display
#========================================================================
pid=$(pidof xfce4-display-settings)
if [ $? -ne 0 ]; then
    xfce4-display-settings
else
    wid=$(xdotool search --onlyvisible --pid $pid)
    xdotool windowactivate $wid
fi
exit 0
